name: Test
on:
  pull_request:
  push:
    branches:
      - rtia_fix_generation

jobs:
  sqlite:
    name: Run tests with sqlite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build & run
        run: docker run --rm $(docker build -q --file ./ci/docker/sqlite.Dockerfile .)
  duckdb:
    name: Run tests with duckdb
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build & run
        run: docker run --rm $(docker build -q --file ./ci/docker/duckdb.Dockerfile .)
  datafusion:
    name: Run tests with datafusion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build & run
        run: docker run --rm $(docker build -q --file ./ci/docker/datafusion.Dockerfile .)
  postgres:
    name: Run tests with postgres
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build
        run: docker-compose -f ./ci/docker/postgres-compose.yaml build

      - name: Run
        run: docker-compose -f ./ci/docker/postgres-compose.yaml run app
  velox:
    name: Run tests with velox
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build
        run: docker-compose -f ./ci/docker/velox-compose.yaml build

      - name: Run
        run: docker-compose -f ./ci/docker/velox-compose.yaml run app
  site:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - run: pip install -r requirements.txt
      - name: Build Site
        run: python build_site.py
